// "use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ProviderWrapper from './ProviderWrapper';
import { Navbar, Footer } from './components'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Pokemon.com",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderWrapper>
          <div className="flex flex-col min-h-screen">
            <Navbar />
            <main className="flex-grow">{children}</main>
            <Footer />
          </div>
        </ProviderWrapper>
      </body>
    </html>
  );
}
